/**
 * Dashboard Page - Next.js 14 App Router
 * Generated by HubLab Studio V2
 *
 * Features:
 * - SWR data fetching with auto-refresh
 * - Loading states
 * - Error handling
 * - Responsive design
 * - Real-time metrics
 * - Interactive charts
 */

'use client';

import { useState, useMemo } from 'react';
import useSWR from 'swr';

// Types
interface UserData {
  id: string;
  name: string;
  email: string;
  status: 'active' | 'inactive';
  lastSeen: string;
  plan: string;
}

interface MetricData {
  label: string;
  value: number;
  change: number;
  trend: 'up' | 'down';
}

interface ChartDataPoint {
  month: string;
  revenue: number;
  users: number;
}

// Fetcher function for SWR
const fetcher = async (url: string) => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error('Failed to fetch data');
  }
  return response.json();
};

// Mock data generator (replace with real API)
const generateMockData = () => {
  return {
    metrics: [
      {
        label: 'Total Revenue',
        value: 84523,
        change: 12.5,
        trend: 'up' as const
      },
      {
        label: 'Active Users',
        value: 2453,
        change: 8.2,
        trend: 'up' as const
      },
      {
        label: 'New Signups',
        value: 345,
        change: -3.1,
        trend: 'down' as const
      },
      {
        label: 'Conversion Rate',
        value: 3.8,
        change: 0.4,
        trend: 'up' as const
      }
    ],
    chartData: [
      { month: 'Jan', revenue: 45000, users: 1850 },
      { month: 'Feb', revenue: 52000, users: 2100 },
      { month: 'Mar', revenue: 48000, users: 2050 },
      { month: 'Apr', revenue: 61000, users: 2300 },
      { month: 'May', revenue: 72000, users: 2450 },
      { month: 'Jun', revenue: 84523, users: 2453 }
    ],
    users: [
      {
        id: '1',
        name: 'Alice Johnson',
        email: 'alice@example.com',
        status: 'active' as const,
        lastSeen: '2 minutes ago',
        plan: 'Pro'
      },
      {
        id: '2',
        name: 'Bob Smith',
        email: 'bob@example.com',
        status: 'active' as const,
        lastSeen: '1 hour ago',
        plan: 'Team'
      },
      {
        id: '3',
        name: 'Carol Williams',
        email: 'carol@example.com',
        status: 'inactive' as const,
        lastSeen: '3 days ago',
        plan: 'Starter'
      },
      {
        id: '4',
        name: 'David Brown',
        email: 'david@example.com',
        status: 'active' as const,
        lastSeen: '30 minutes ago',
        plan: 'Pro'
      },
      {
        id: '5',
        name: 'Emma Davis',
        email: 'emma@example.com',
        status: 'active' as const,
        lastSeen: '5 minutes ago',
        plan: 'Team'
      },
      {
        id: '6',
        name: 'Frank Miller',
        email: 'frank@example.com',
        status: 'active' as const,
        lastSeen: '1 hour ago',
        plan: 'Starter'
      },
      {
        id: '7',
        name: 'Grace Wilson',
        email: 'grace@example.com',
        status: 'inactive' as const,
        lastSeen: '1 week ago',
        plan: 'Pro'
      },
      {
        id: '8',
        name: 'Henry Moore',
        email: 'henry@example.com',
        status: 'active' as const,
        lastSeen: '15 minutes ago',
        plan: 'Team'
      }
    ]
  };
};

// Metric Card Component
const MetricCard = ({ metric }: { metric: MetricData }) => {
  const isPercentage = metric.label.includes('Rate');
  const isCurrency = metric.label.includes('Revenue');

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200 hover:shadow-md transition">
      <div className="flex justify-between items-start mb-2">
        <p className="text-sm font-medium text-gray-600">{metric.label}</p>
        <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-semibold ${
          metric.trend === 'up' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
        }`}>
          {metric.trend === 'up' ? '↑' : '↓'} {Math.abs(metric.change)}%
        </span>
      </div>
      <p className="text-3xl font-bold text-gray-900">
        {isCurrency && '$'}
        {metric.value.toLocaleString()}
        {isPercentage && '%'}
      </p>
      <p className="text-sm text-gray-500 mt-2">vs last month</p>
    </div>
  );
};

// Simple Bar Chart Component
const BarChart = ({ data }: { data: ChartDataPoint[] }) => {
  const maxRevenue = Math.max(...data.map(d => d.revenue));

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
      <h3 className="text-lg font-semibold text-gray-900 mb-6">Revenue Trend</h3>
      <div className="space-y-4">
        {data.map((point, index) => (
          <div key={index} className="flex items-center gap-4">
            <span className="text-sm font-medium text-gray-600 w-12">{point.month}</span>
            <div className="flex-1 relative">
              <div className="bg-gray-100 rounded-full h-8 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-blue-500 to-purple-500 h-full rounded-full transition-all duration-500 flex items-center justify-end pr-3"
                  style={{ width: `${(point.revenue / maxRevenue) * 100}%` }}
                >
                  <span className="text-xs font-semibold text-white">
                    ${(point.revenue / 1000).toFixed(0)}k
                  </span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// Line Chart Component (simplified SVG)
const LineChart = ({ data }: { data: ChartDataPoint[] }) => {
  const maxUsers = Math.max(...data.map(d => d.users));
  const minUsers = Math.min(...data.map(d => d.users));
  const range = maxUsers - minUsers;

  const points = data.map((point, index) => {
    const x = (index / (data.length - 1)) * 100;
    const y = 100 - (((point.users - minUsers) / range) * 80 + 10);
    return `${x},${y}`;
  }).join(' ');

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
      <h3 className="text-lg font-semibold text-gray-900 mb-6">User Growth</h3>
      <svg viewBox="0 0 100 100" className="w-full h-48" preserveAspectRatio="none">
        <defs>
          <linearGradient id="lineGradient" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#3B82F6" />
            <stop offset="100%" stopColor="#8B5CF6" />
          </linearGradient>
        </defs>
        <polyline
          points={points}
          fill="none"
          stroke="url(#lineGradient)"
          strokeWidth="2"
          vectorEffect="non-scaling-stroke"
        />
        {data.map((point, index) => {
          const x = (index / (data.length - 1)) * 100;
          const y = 100 - (((point.users - minUsers) / range) * 80 + 10);
          return (
            <circle
              key={index}
              cx={x}
              cy={y}
              r="1.5"
              fill="#3B82F6"
              vectorEffect="non-scaling-stroke"
            />
          );
        })}
      </svg>
      <div className="flex justify-between mt-4 text-xs text-gray-600">
        {data.map((point, index) => (
          <span key={index}>{point.month}</span>
        ))}
      </div>
    </div>
  );
};

// User Table Component
const UserTable = ({ users, isLoading }: { users: UserData[]; isLoading: boolean }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'inactive'>('all');

  const filteredUsers = useMemo(() => {
    return users.filter(user => {
      const matchesSearch = user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           user.email.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesStatus = statusFilter === 'all' || user.status === statusFilter;
      return matchesSearch && matchesStatus;
    });
  }, [users, searchTerm, statusFilter]);

  if (isLoading) {
    return (
      <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
        <div className="animate-pulse space-y-4">
          <div className="h-10 bg-gray-200 rounded"></div>
          <div className="h-64 bg-gray-200 rounded"></div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-200">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
        <h3 className="text-lg font-semibold text-gray-900">Recent Users</h3>
        <div className="flex gap-3 w-full md:w-auto">
          <input
            type="text"
            placeholder="Search users..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="flex-1 md:w-64 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as any)}
            className="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
          >
            <option value="all">All Status</option>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-200">
              <th className="text-left py-3 px-4 text-sm font-semibold text-gray-600">User</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-gray-600">Status</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-gray-600">Plan</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-gray-600">Last Seen</th>
              <th className="text-left py-3 px-4 text-sm font-semibold text-gray-600">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredUsers.length === 0 ? (
              <tr>
                <td colSpan={5} className="text-center py-8 text-gray-500">
                  No users found
                </td>
              </tr>
            ) : (
              filteredUsers.map((user) => (
                <tr key={user.id} className="border-b border-gray-100 hover:bg-gray-50 transition">
                  <td className="py-4 px-4">
                    <div>
                      <p className="font-medium text-gray-900">{user.name}</p>
                      <p className="text-sm text-gray-500">{user.email}</p>
                    </div>
                  </td>
                  <td className="py-4 px-4">
                    <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold ${
                      user.status === 'active'
                        ? 'bg-green-100 text-green-800'
                        : 'bg-gray-100 text-gray-800'
                    }`}>
                      {user.status}
                    </span>
                  </td>
                  <td className="py-4 px-4 text-gray-700">{user.plan}</td>
                  <td className="py-4 px-4 text-sm text-gray-600">{user.lastSeen}</td>
                  <td className="py-4 px-4">
                    <button className="text-blue-600 hover:text-blue-800 text-sm font-medium">
                      View Details
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="mt-4 flex justify-between items-center text-sm text-gray-600">
        <p>Showing {filteredUsers.length} of {users.length} users</p>
        <div className="flex gap-2">
          <button className="px-3 py-1 border border-gray-300 rounded hover:bg-gray-50">Previous</button>
          <button className="px-3 py-1 bg-blue-600 text-white rounded">1</button>
          <button className="px-3 py-1 border border-gray-300 rounded hover:bg-gray-50">2</button>
          <button className="px-3 py-1 border border-gray-300 rounded hover:bg-gray-50">Next</button>
        </div>
      </div>
    </div>
  );
};

// Main Dashboard Page
export default function DashboardPage() {
  // Use SWR for data fetching with auto-refresh
  // In production, replace '/api/dashboard' with your actual API endpoint
  const { data, error, isLoading, mutate } = useSWR(
    '/api/dashboard',
    // For demo purposes, return mock data directly
    () => Promise.resolve(generateMockData()),
    {
      refreshInterval: 30000, // Refresh every 30 seconds
      revalidateOnFocus: true,
      dedupingInterval: 5000
    }
  );

  const handleRefresh = () => {
    mutate();
  };

  // Error state
  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-xl p-8 shadow-lg max-w-md w-full text-center">
          <div className="text-red-500 text-5xl mb-4">⚠️</div>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">Error Loading Dashboard</h2>
          <p className="text-gray-600 mb-6">{error.message}</p>
          <button
            onClick={handleRefresh}
            className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  // Loading state
  if (isLoading || !data) {
    return (
      <div className="min-h-screen bg-gray-50 p-4 md:p-8">
        <div className="max-w-7xl mx-auto space-y-6">
          <div className="h-12 bg-white rounded-lg animate-pulse"></div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="h-32 bg-white rounded-xl animate-pulse"></div>
            ))}
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="h-80 bg-white rounded-xl animate-pulse"></div>
            <div className="h-80 bg-white rounded-xl animate-pulse"></div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 md:px-8 py-4">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
              <p className="text-sm text-gray-600">Welcome back! Here's your overview</p>
            </div>
            <button
              onClick={handleRefresh}
              disabled={isLoading}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition disabled:opacity-50"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Refresh
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto p-4 md:p-8 space-y-6">
        {/* Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {data.metrics.map((metric, index) => (
            <MetricCard key={index} metric={metric} />
          ))}
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <BarChart data={data.chartData} />
          <LineChart data={data.chartData} />
        </div>

        {/* User Table */}
        <UserTable users={data.users} isLoading={isLoading} />
      </main>
    </div>
  );
}
